version: "3"

services:
  hello-api:
    image: tolentino/hello-api
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
